// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzm1dJoBZUIjrsF5EurNT48vkFLcsX_Ic',
    appId: '1:1024000105622:web:f114904d40a7dd7414b6b7',
    messagingSenderId: '1024000105622',
    projectId: 'mingle-411805',
    authDomain: 'mingle-411805.firebaseapp.com',
    storageBucket: 'mingle-411805.appspot.com',
    measurementId: 'G-BBYMPQNB5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZEBv352_Ug4FpVFLQT-zj5CS0_4SixM',
    appId: '1:1024000105622:android:3630c5b45522b78e14b6b7',
    messagingSenderId: '1024000105622',
    projectId: 'mingle-411805',
    storageBucket: 'mingle-411805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS-y8M73i2-zaAlnDNC1MAz_llc61GbLc',
    appId: '1:1024000105622:ios:c629875d281531ff14b6b7',
    messagingSenderId: '1024000105622',
    projectId: 'mingle-411805',
    storageBucket: 'mingle-411805.appspot.com',
    androidClientId: '1024000105622-euau9pdgtctaiift2vs47lsmp9ekuhi1.apps.googleusercontent.com',
    iosBundleId: 'com.sooming.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS-y8M73i2-zaAlnDNC1MAz_llc61GbLc',
    appId: '1:1024000105622:ios:c629875d281531ff14b6b7',
    messagingSenderId: '1024000105622',
    projectId: 'mingle-411805',
    storageBucket: 'mingle-411805.appspot.com',
    androidClientId: '1024000105622-euau9pdgtctaiift2vs47lsmp9ekuhi1.apps.googleusercontent.com',
    iosBundleId: 'com.sooming.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzm1dJoBZUIjrsF5EurNT48vkFLcsX_Ic',
    appId: '1:1024000105622:web:19c1c3871d67949414b6b7',
    messagingSenderId: '1024000105622',
    projectId: 'mingle-411805',
    authDomain: 'mingle-411805.firebaseapp.com',
    storageBucket: 'mingle-411805.appspot.com',
    measurementId: 'G-BZN6J46X7L',
  );

}